### ISSUE TITLE
[BUG] Router doesn't pick a standard Kubernetes Ingress, works with route

### ISSUE THREAD

**Issue by carlosedp** [redhat-et/microshift#222]
#### What happened:

When I try to expose a service using MicroShift router by using a default Kubernetes Ingress, the router doesn't pick the ingress and publish it.

When using a route, it works. I'm using the HAProxy router.

#### What you expected to happen:

Both routes and ingresses to work with the HAproxy router.

#### How to reproduce it (as minimally and precisely as possible):

For example with an app created with:

```
kubectl create deployment echo -n default --image=docker.io/carlosedp/echo-demo
kubectl expose deploy echo -n default --port=80 --target-port=8080
```

1. Create an application and service.
2. Expose it thru a route with `oc expose svc/echo -n default --hostname=echo.192.168.1.17.nip.io` works. Eg. `curl echo.192.168.1.17.nip.io`
3. Expose using ingress below, it doesn't work.

```
cat <<EOF | kubectl apply -f -
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
  namespace: default
spec:
  rules:
    - host:  echo.192.168.1.17.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo
                port:
                  number: 8080
EOF
```
 
#### Environment:
- Microshift version (use `microshift version`): Latest from main branch
- Hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:
