### ISSUE TITLE
[BUG] MicroShift OpenAPIV3Schema validation errors

### ISSUE THREAD

**Issue by sallyom** [redhat-et/microshift#480]
#### What happened:

If I try to create an SCC (probably any resource?) that doesn't explicitly include a required but nullable: true field in the yaml def, like, `priority: 0` or `defaultAddCapabilities: null` microshift errors. However, the same oc with a 4.8 OCP does not error, it happily creates the resource and sets the nullable: true fields to their empty value (0, null).

#### What you expected to happen:

Same behavior as OpenShift

#### How to reproduce it (as minimally and precisely as possible):

I discovered this while trying to deploy volsync in MicroShift, hence the volsync-mover SCC.
Try to apply this file with both MicroShift and an OCP 4.8 cluster:
(I have a very new `oc` 4.9.8) 

```
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: volsync-mover
  labels:
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
  - AUDIT_WRITE
  - SYS_CHROOT
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
```

#### Anything else we need to know?:

SCC definition in MicroShift from vendored openshift/api
If you add these to the above yaml, MicroShift will succeed in creating the SCC:

```
priority: 0
defaultAddCapabilities: null
```

#### Environment:
- Microshift version (use `microshift version`): latest from main branch
- Hardware configuration:
- OS (e.g: `cat /etc/os-release`): Centos 8 Stream, podman running MicroShift (not AIO)

#### Relevant Logs 

```
The SecurityContextConstraints "volsync-mover" is invalid: 
* defaultAddCapabilities: Required value
* priority: Required value
```
